django_python/projeto/projeto/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name = 'index.html'), name='index'),
    url(r'^reservas/', include('reservas.urls', namespace='reservas')),
    path('admin/', admin.site.urls),
]

django_python/projeto/reservas/urls.py
from django.conf.urls import url
from . import views

app_name = 'reservas'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<cliente_id>[0-9]+)/$',views.detalhe, name='detalhe'),
    url(r'^(?P<cliente_id>[0-9]+)/lista/$',views.reservas, name='reservas'),
    url(r'^(?P<cliente_id>[0-9]+)/confirma/$',views.confirma, name='confirma'),
    url(r'^obrigado/$', views.obrigado, name='obrigado'),
    url(r'^contato/$', views.contato, name='contato'),

]

django_python/projeto/reservas/models.py
import datetime

from django.db import models

# Create your models here.
from django.utils import timezone


class Cliente(models.Model):
    nome = models.CharField(max_length=200)
    endereco = models.CharField(max_length=200)
    telefone = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    registrado_em = models.DateTimeField('data do registro')

    def reservas_nao_confirmadas(self):
        return self.reserva_set.filter(confirmada=False)


    def reservas_confirmadas(self):
        return self.reserva_set.filter(confirmada=True)


    def __str__(self):
        return self.nome

    def registro_eh_antigo(self):
        um_ano = timezone.now() - datetime.timedelta(days=365)
        return self.registrado_em < um_ano

    registro_eh_antigo.admin_order_field = 'registrado em'
    registro_eh_antigo.boolean = True
    registro_eh_antigo.short_description = 'Cliente Antigo?'




class Reservas(models.Model):
    data_reserva = models.DateTimeField('data da reserva')
    data_evento = models.DateTimeField('data do evento')
    pessoas = models.IntegerField(default=0)
    confirmada = models.BooleanField(default=False)
    cliente = models.ForeignKey(Cliente, on_delete=type)

    def __str__(self):
        return '{} - {}'.format(self.cliente, str(self.data_evento))

django_python/projeto/reservas/forms.py
from django import forms

class formContato(forms.Form):
    email = forms.EmailField()
    assunto = forms.CharField(label='Assunto', max_length=150)
    comentarios = forms.CharField(label='Comentarios', widget= forms.Textarea)

django_python/projeto/reservas/views.py
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Cliente, Reservas
from .forms import formContato

# Create your views here.

def index(request):
    ultimos_clientes = Cliente.objects.order_by('-registrado_em')[:5]
    context = {'ultimos_clientes' : ultimos_clientes, }
    return render(request, 'reservas/index.html', context)


def detalhe(request, cliente_id):
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Cliente.DoesNotExist:
        raise Http404("Cliente não existe")
    return render(request, 'reservas/detalhe.html', {'cliente': cliente})


def reservas(request, cliente_id):
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Cliente.DoesNotExist:
        raise Http404("Cliente não existe")

    return render(request, 'reservas/lista.html', {'cliente': cliente})


def confirma(request, cliente_id):
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Cliente.DoesNotExist:
        raise Http404("Cliente não existe")

    confirmados = request.POST.getlist('confirmacao')
    for reserva_id in confirmados:
        try:
            reserva = cliente.reserva_set.get(pk=reserva_id)
        except (KeyError, Reservas.DoesNotExist):
            return render(request, 'reservas/detalhe.html', {'cliente': cliente,
                                                            'error_message': "Reserva nao encontrada"})
        else:
            reserva.confirmada = True
            reserva.save()
        return HttpResponseRedirect(reverse('reservas:reservas', args=(cliente.id)))

def contato(request):
    if request.method == 'POST':
        form = formContato(request.POST)
        if form.is_valid():
            assunto = form.cleaned_data['assunto']
            comentarios = form.cleaned_data['comentarios']
            remetente = form.cleaned_data['email']
            destinatarios = ['duartelgk4@gmail.com']
            try:
                send_mail(assunto, comentarios, remetente, destinatarios)
            except BadHeaderError:
                return HttpResponse('Cabeçalho Inválido!!!')
            return HttpResponseRedirect('/reservas/obrigado/')

    else:
        form = formContato()

    return render(request, 'reservas/contato.html', {'form': form})

def obrigado(request):
    return render(request, 'reservas/obrigado.html')

django_python/projeto/projeto/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Template Pai</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <meta http-equiv="Content-Type" content="text/html">
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
</head>

<body>
    {% block header%}
    <header></header>
    {% endblock %}

        <nav class="navbar">
            <a href="{% url 'index' %}">
                <div id="inicio" class="navButtons"></div>
            </a> -
            <a href="{% url 'reservas:index' %}">
                <div id="reservas" class="navButtons"></div>
            </a> -
            <div id="cardapio" class="navButtons"></div>

            <a href="{% url 'reservas:contato' %}">
            <div id="contato" class="navButtons"></div>
            </a>

        </nav>
    <section id="body">
        <div class="conteudo">
            {% block conteudo %}

            {% endblock %}
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

django_python/projeto/projeto/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Inicio</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block conteudo %}
        <h1>Restaurante Sabor do Sertão</h1>
        <p>Bem Vindo ao verdadeiro!</p>
    {% endblock %}

</body>
</html>

django_python/projeto/reservas/templates/reservas/contato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contatos</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block conteudo %}
        <form action="{% url 'reservas:contato' %}" method="post" class="elegant-aero">
            {% csrf_token %}
            {{form.as_ul}}
            <input type="submit" value="Enviar" class="btn btn-primary">
        </form>
    {% endblock %}
</body>
</html>

django_python/projeto/reservas/templates/reservas/detalhe.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Página de Detalhe</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block conteudo %}
    <h1>{{cliente.nome}}</h1>
    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'reservas:confirma' cliente.id %}" method="post">
        {% csrf_token %}
        {% for reserva in cliente.reservas_set.all %}
        <input type="checkbox" name="confirmacao" id="confirmacao{{forloop.counter}}"
        value="{{reserva.id}}" {% if reserva.confirmada %}checked{% endif %}>

        <label for="confirmacao{{forloop.counter}}">
            Confirmar? - {{reserva.data_evento}} - {{reserva.pessoas}} pessoas
        </label><br>
        {% endfor %}
        <input type="submit" value="Atualizar" class="btn btn-primary">
    </form>
    {% endblock %}
</body>
</html>

django_python/projeto/reservas/templates/reservas/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Pagina Inicial</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block conteudo %}
    {% if ultimos_clientes %}
    <ul>
        {% for cliente in ultimos_clientes %}
        <li>
            <a href="/reservas/{{cliente.id}}">{{cliente.nome}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhum Cliente Cadastrado</p>
    {% endif %}

    <h1>Metodo para Criar links para detalhes</h1>
    {% if ultimos_clientes %}
    <ul>
        {% for cliente in ultimos_clientes %}
        <li>
            <a href="{% url 'reservas:detalhe' cliente.id %}">{{cliente.nome}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhum Cliente Cadastrado</p>
    {% endif %}
    {% endblock %}
</body>
</html>

django_python/projeto/reservas/templates/reservas/lista.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Lista Reservas</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block conteudo %}
    <h1>{{cliente.nome}}</h1>
    <ul>
        {% for reserva in cliente.reservas_confirmadas %}
        <li>
            Data da Reserva: {{reserva.data_reserva}}<br>
            Data do Evento: {{reserva.data_evento}}<br>
            Quantidade de Pessoas: {{reserva.pessoas}}
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'reservas:detalhe' cliente.id%}">
        Deseja confirmar mais reservas?
    </a>
    {% endblock %}
</body>
</html>

django_python/projeto/reservas/templates/reservas/obrigado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Obrigado</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block conteudo %}
    <p>Recebemos sua Mensagem!</p>
    <p>Entraremos em contato em breve.</p>
    {% endblock %}
</body>
</html>